/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import temp.ObjectSend;
import temp.UserDTO;

/**
 *
 * @author lpphu
 */
public class EditGroupDialog extends javax.swing.JFrame {
    FormatTable formatTable = new FormatTable();
    DefaultTableModel model = new DefaultTableModel();
    private ArrayList<JCheckBox> arrBox = new ArrayList<>();
    public static ArrayList<UserDTO> arrMember = new ArrayList<>();
    public static ArrayList<UserDTO> arrFriend = new ArrayList<>();
    public static String groupName = "";
    
    /**
     * Creates new form addGroupDialog
     */
    public EditGroupDialog() {
        initComponents();
        friendTableFormat();
        nameTxt.setText(groupName);
        friendPanel.setLayout(new GridLayout(arrFriend.size()+2, 1));
        readMember();
        readFriend();

    }
    public void readFriend()
    {
        if(!arrFriend.isEmpty())
        {
            for (UserDTO user : arrFriend) 
            {
                JPanel p = new JPanel(null);
                p.setBackground(Color.white);
                p.setPreferredSize(new Dimension(200, 40));
                //p.setBorder(new LineBorder(Color.black, 2));
                JCheckBox check = new JCheckBox(user.getUser_name() + " - " + user.getUser_email());
                arrBox.add(check);
                check.setFont(new Font("Time New Roman", Font.BOLD, 12));
                check.setBounds(5, 0, 200, 40);
                p.add(check);
                friendPanel.add(p);
            }
        }

    }
    public void readMember()
    {
        if(!arrMember.isEmpty())
        {
            try
            {
            int rowCount = model.getRowCount();//remove all row
            for (int i = rowCount - 1; i >= 0; i--) 
            {
                model.removeRow(i);
            }
            for(UserDTO str : arrMember)
            {
                Vector row = new Vector();
                row.add(str.getUser_name());
                row.add(str.getGroup_member_joinday());
                model.addRow(row);
            }
            memberTable.setModel(model);
        
        } catch(Exception e) {
            e.printStackTrace();
        }
        }
    }
    public void friendTableFormat()
    {
        formatTable.formatTablenoIcon(memberTable);
        Vector header = new Vector();
        header.add("Tên");
        header.add("Ngày tham gia");
        if (model.getRowCount()==0)
        { 
                model=new DefaultTableModel(header,0){
                @Override//No edit
                public boolean isCellEditable(int row, int column) 
                {       
                        return false;
                }
            };
        } 
        memberTable.setModel(model);
        
//        table.getColumnModel().getColumn(0).setPreferredWidth(30);
//        table.getColumnModel().getColumn(1).setPreferredWidth(230);
//        table.getColumnModel().getColumn(2).setPreferredWidth(40);
    }
    
    public void editGroup(String groupName)
    {
        ArrayList<String> infos = new ArrayList<>();
        for (JCheckBox checkBox : arrBox) 
        {
            if (checkBox.isSelected()) 
            {
                infos.add(checkBox.getText().split("-")[1].trim());
            }
        }
        
        ObjectSend obj = new ObjectSend(infos, "edit_group_info", groupName, GroupChatPanel.currentGroupId);
        OverrallFrame.write(obj);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        errorLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SỬA THÔNG TIN NHÓM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 620, 27));

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-20.png"))); // NOI18N
        saveBtn.setText("Hoàn tất");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 120, 30));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Thành viên hiện tại");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tên nhóm:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        friendPanel.setBackground(new java.awt.Color(255, 255, 255));
        friendPanel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(friendPanel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, 160));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Thêm thành viên");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(memberTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 320, 160));

        errorLb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        errorLb.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(errorLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        if(name.equals(""))
        {
            errorLb.setText("Tên nhóm không được để trống!");
        } else if (name.length() > 20)
        {
            errorLb.setText("Tên nhóm không được quá 20 ký tự!");
        } else {
            errorLb.setText("");
            editGroup(name);
            this.dispose();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGroupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGroupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGroupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGroupDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGroupDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLb;
    private javax.swing.JPanel friendPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable memberTable;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
