/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import com.toedter.calendar.JTextFieldDateEditor;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import temp.ObjectSend;
import temp.UserDTO;

/**
 *
 * @author Nam
 */
public class EditUserPanel extends javax.swing.JPanel {
    JTextFieldDateEditor ngaysinhTxt;
    public static UserDTO currentUser;
    /**
     * Creates new form EmployeePanel
     */
    public EditUserPanel() {
        initComponents();
        init();
    }
    
    public void init()
    {        
        ngaysinhTxt = (JTextFieldDateEditor) dateTxt.getDateEditor();
        ngaysinhTxt.setEditable(false);
        
        if(currentUser != null)
        {
            tenTxt.setText(currentUser.getUser_name());
            sdtTxt.setText(currentUser.getUser_phone());
            ngaysinhTxt.setText(currentUser.getUser_birthday());
            combobox.setSelectedItem(currentUser.getUser_gender());
        }
    }
    
    
    public void editInfo()
    {
        if(check())
        {
            UserDTO dto = new UserDTO(OverrallFrame.userEmail, tenTxt.getText(), ngaysinhTxt.getText(), sdtTxt.getText(), combobox.getSelectedItem().toString());
            ObjectSend obj = new ObjectSend("edit_user_info", dto);
            OverrallFrame.write(obj);
            JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!");
        }
    }
    public void changePass()
    {
        try
        {
        String mkcu = md5(mkcuTxt.getText());//change to md5
        if(mkcuTxt.getText().equals(""))
        {
            mkErr.setText("Chưa nhập mật khẩu cũ");
        } else if (mkmoiTxt.getText().equals(""))
        {
            mkErr.setText("Chưa nhập mật khẩu mới");
        }
        else if (!mkcu.equals(currentUser.getUser_password())) {
            mkErr.setText("Mật khẩu cũ không đúng");
        } else {
            ObjectSend obj = new ObjectSend("edit_user_pass", OverrallFrame.userEmail, md5(mkmoiTxt.getText()));
            OverrallFrame.write(obj);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công! Vui lòng đăng nhập lại!");
            mkErr.setText("");
            OverrallFrame.logoutBtn.doClick();
        }
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    public boolean check()
    {
        boolean check = true;
        if(tenTxt.getText().length() > 20)
        {
            tenErr.setText("Tên không được vượt quá 20 kí tự");
            check = false;
        } else {
            tenErr.setText("");
        }
        //---------------------------------
        if(!sdtTxt.getText().equals(""))
        {
            if (sdtTxt.getText().length() != 10 || sdtTxt.getText().charAt(0) != '0') 
            {
                sdtErr.setText("Không đúng định dạng SĐT");
                check = false;
            } else {
                sdtErr.setText("");
            }
        }
        //---------------------------------
        Date today = new Date();
        if(!ngaysinhTxt.getText().equals(""))
        {
            if (dateTxt.getDate().after(today)) {
                ngaysinhErr.setText("Ngày sinh không hợp lý");
                check = false;
            } else {
                ngaysinhErr.setText("");
            }
        }
        return check;
    }
    public String md5(String msg) throws Exception {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] mdByte = md.digest(msg.getBytes());
        BigInteger no = new BigInteger(1, mdByte);
        String hashtext = no.toString(16);
        while (hashtext.length() < 32) {
            hashtext = "0" + hashtext;
        }
        return hashtext;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ngaysinhErr = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tenTxt = new javax.swing.JTextField();
        tenErr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sdtErr = new javax.swing.JLabel();
        sdtTxt = new javax.swing.JTextField();
        dateTxt = new com.toedter.calendar.JDateChooser();
        saveBtn = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        changePass = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mkmoiTxt = new javax.swing.JTextField();
        mkcuTxt = new javax.swing.JTextField();
        mkErr = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(51, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Chọn giới tính:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-hand-with-pen-20.png"))); // NOI18N
        jLabel1.setText(" SỬA THÔNG TIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        ngaysinhErr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ngaysinhErr.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(ngaysinhErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 480, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Nhập tên:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));
        jPanel1.add(tenTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 650, 30));

        tenErr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        tenErr.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(tenErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Nhập số điện thoại:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        sdtErr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        sdtErr.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(sdtErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 480, 30));
        jPanel1.add(sdtTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 650, 30));

        dateTxt.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 650, 30));

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-20.png"))); // NOI18N
        saveBtn.setText("Sửa thông tin");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 30));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Chọn ngày sinh:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changePass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        changePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-privacy-20.png"))); // NOI18N
        changePass.setText("Đổi mật khẩu");
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });
        jPanel2.add(changePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Mật khẩu cũ:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Mật khẩu mới:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));
        jPanel2.add(mkmoiTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 30));
        jPanel2.add(mkcuTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 230, 30));

        mkErr.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        mkErr.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(mkErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 390, 170));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Xác nhận sửa thông tin?", "Sửa thông tin", JOptionPane.WARNING_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) 
        {
            editInfo();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Xác nhận đổi mật khẩu?", "Sửa thông tin", JOptionPane.WARNING_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) 
        {
            changePass();
        }
    }//GEN-LAST:event_changePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePass;
    private javax.swing.JComboBox<String> combobox;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mkErr;
    private javax.swing.JTextField mkcuTxt;
    private javax.swing.JTextField mkmoiTxt;
    private javax.swing.JLabel ngaysinhErr;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel sdtErr;
    private javax.swing.JTextField sdtTxt;
    private javax.swing.JLabel tenErr;
    private javax.swing.JTextField tenTxt;
    // End of variables declaration//GEN-END:variables
}
