package client;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import org.jsoup.Connection;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import server.cipher;

/**
 *
 * @author MY PC
 */
public class loginForm extends javax.swing.JFrame {

    public static IvParameterSpec ivParameterSpec;
    static String key;
    private static boolean checkCode = false;
    private Thread thread;
    private BufferedWriter os;
    private BufferedReader is;
    private Socket socketClient;
    private List<String> onlineList;
    private int id;
    Thread th;
    RegisterForm regF;
    cipher c = new cipher();
    String ipServer;

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        try {
            initComponents();
            setSize(496,375);
            this.setLocationRelativeTo(null);
            setVisible(true);
            socketClient = new Socket(getIpServer(), 9999);
            System.out.println("Kết nối thành công!");
            connectServer();
        } catch (IOException ex) {
            //ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Server đang đóng!");
            dispose();
        }
        

    }
    public String getIpServer()
    {
        String res = "localhost";
        try
        {
        String api = "https://api-generator.retool.com/CYBXDG/data/1";
        Document doc =  Jsoup.connect(api).ignoreContentType(true).ignoreHttpErrors(true)
                .header("Content-Type", "application/json")
                .method(Connection.Method.GET)
                .execute().parse();
        JSONObject data = new JSONObject(doc.text());
        System.out.println(data.get("ip"));
        res = data.get("ip").toString();
        } catch(Exception e)
        {
            e.printStackTrace();
        }
        return res;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsername1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jCheckBoxShowPass1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png")));
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(176, 176, 176)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        body.setBackground(new java.awt.Color(0, 204, 204));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-businessman-30.png")));
        jLabel5.setText("Username");
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 140, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-privacy-30.png")));
        jLabel6.setText("Password");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 28));

        jTextFieldUsername1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUsername1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsername1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsername1KeyPressed(evt);
            }
        });
        body.add(jTextFieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 196, -1));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        body.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 196, -1));

        jCheckBoxShowPass1.setForeground(new java.awt.Color(51, 0, 255));
        jCheckBoxShowPass1.setText("Show pass");
        jCheckBoxShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPass1ActionPerformed(evt);
            }
        });
        body.add(jCheckBoxShowPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 85, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-privacy-30.png")));
        jLabel4.setText("Username hoặc Password không đúng");
        jLabel4.setVisible(false);
        body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 20, 380, 59));

        jButtonRegister.setBackground(new java.awt.Color(51, 51, 255));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 0, 102));
        jButtonRegister.setText("Register");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        body.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jButtonLogin.setBackground(new java.awt.Color(51, 51, 255));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 0, 102));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        body.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 93, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void connectServer() {
        try {
            thread = new Thread() {
                @Override
                public void run() {
                    try {
//                        socketClient = new Socket("localhost", 9999);
//                        System.out.println("Kết nối thành công!");
                        os = new BufferedWriter(new OutputStreamWriter(socketClient.getOutputStream()));
                        is = new BufferedReader(new InputStreamReader(socketClient.getInputStream()));
                        String msg;
                        key = is.readLine();
                        System.out.println("key "+key);
                        while (true) {
                            msg = c.decrypt(is.readLine(), key);
                            if (msg.equals("login-sucess")) {
                                //login
                                OverrallFrame.userEmail = jTextFieldUsername1.getText();
                                OverrallFrame ok = new OverrallFrame(socketClient, key);
                                ok.setVisible(true);
                                //close
                               
                                dispose();
                                break;
                            } else if (msg.equals("block")) {
                                JOptionPane.showMessageDialog(body, "Tài khoản của bạn đã bị ban");
                            }else if (msg.equals("login-fail")) {
                                System.out.println("Tài khoản hoặc mật khẩu không chính xác");
                                jLabel4.setVisible(true);
                            } else if (msg.equals("signup-fail")) {
                                regF.notify("Mã OTP sai");
                            } else if (msg.equals("signup-success")) {
                                regF.setVisible(false);
                                setVisible(true);
                            } else if (msg.equals("send-success")) {
                                regF.notify("Gửi mã OTP qua email thành công");
                            } else if (msg.equals("send-fail")) {
                                regF.notify("Mã OTP đã gửi qua email có hiệu lực 10 phút");
                            } else if (msg.equals("sendmail-fail")) {
                                regF.notify("Email đã được đăng ký");
                            } else if (msg.equals("ban")) {
//                                client.setVisible(false);
                                setVisible(true);
                                break;
                            } else if (msg.equals("login")) {
                                regF.setVisible(false);
                                setVisible(true);
                            } else {
                                System.out.println(msg);
                            }
                        }
                    } catch (UnknownHostException e) {
                        return;
                    } catch (IOException e) {
                        return;
                    }
                }
            };
            thread.run();
        } catch (Exception e) {
        }
    }

    void send(String msg) throws Exception {
        msg = c.encrypt(msg, key);
        os.write(msg);
        os.newLine();
        os.flush();
    }

    void notify(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String user = jTextFieldUsername1.getText();
        String pass = String.valueOf(jPasswordField2.getPassword());
        if (user.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username");
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password");
        } else {
            try {
                send("login-" + user + "-" + pass);
                //send(c.encrypt("login-" + user + "-" + pass, key));

            } catch (Exception ex) {
                Logger.getLogger(loginForm.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        regF = new RegisterForm(is, os);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextFieldUsername1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsername1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsername1KeyPressed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jCheckBoxShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPass1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxShowPass1.isSelected()) {
            jPasswordField2.setEchoChar((char) 0);
        } else {
            jPasswordField2.setEchoChar('*');
        }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxShowPass1ActionPerformed

    void register(String msg) {
        this.setVisible(true);
        //RegisterForm r = new RegisterForm(is,os);
        //if(msg != null) r.notify();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        loginForm a = new loginForm();
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel body;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JCheckBox jCheckBoxShowPass1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldUsername1;
    // End of variables declaration//GEN-END:variables
}
